services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=webrayze'
      - 'POSTGRES_PASSWORD=thisverysecretpassword'
      - 'POSTGRES_USER=inotbaggi'
    ports:
      - '5432'
  service:
    build: .
    ports:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/webrayze
      SPRING_DATASOURCE_USERNAME: inotbaggi
      SPRING_DATASOURCE_PASSWORD: thisverysecretpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    depends_on:
      - postgres
